name: Preprocess Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: python preprocessing/automate_Riyan_Zaenal_Arifin.py

    - name: Upload scaler
      uses: actions/upload-artifact@v4
      with:
        name: scaler
        path: preprocessing/scaler.joblib

    - name: Upload preprocessed data
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-data
        path: preprocessing/heart_preprocessing.csv